import React from 'react'
import Strip from './Strip'

const stripsImg = [[
    'src/assets/img/Clients/Untitled-1-01.png',
'src/assets/img/Clients/Untitled-1-03.png',
'src/assets/img/Clients/Untitled-1-02.png',
'src/assets/img/Clients/Untitled-1-04.png',
'src/assets/img/Clients/lt.png',
'src/assets/img/Clients/Untitled-1-05.png',
'src/assets/img/Clients/bonito.png',
'src/assets/img/Clients/Untitled-1-06.png',
'src/assets/img/Clients/logo1.png',
'src/assets/img/Clients/Untitled-1-07.png',
'src/assets/img/Clients/Untitled-1-08.png',
'src/assets/img/Clients/logo11.png',
'src/assets/img/Clients/Untitled-1-09.png',
'src/assets/img/Clients/graybox.png',
'src/assets/img/Clients/logo48.png',
'src/assets/img/Clients/logo10.png',
'src/assets/img/Clients/Untitled-1-10.png',
'src/assets/img/Clients/logo40.png',
'src/assets/img/Clients/logos-81.png',
'src/assets/img/Clients/logo43.png',
'src/assets/img/Clients/logo5.png',
'src/assets/img/Clients/logo6.png',
'src/assets/img/Clients/logo8.png',
'src/assets/img/Clients/logo2.png',
'src/assets/img/Clients/logo3.png',
'src/assets/img/Clients/logo47.png',
'src/assets/img/Clients/logo51n.png',
'src/assets/img/Clients/logo37.png',
'src/assets/img/Clients/logo20.png',
'src/assets/img/Clients/logo51.png',
'src/assets/img/Clients/logo21.png',
'src/assets/img/Clients/logo38.png',
'src/assets/img/Clients/logo-87.png',
'src/assets/img/Clients/logo64.png',
'src/assets/img/Clients/logo57.png',
'src/assets/img/Clients/logo56.png',
'src/assets/img/Clients/logo52.png',
'src/assets/img/Clients/logo27.png',
'src/assets/img/Clients/logo26.png',
'src/assets/img/Clients/logo15.png',
'src/assets/img/Clients/logo53n.png',
'src/assets/img/Clients/logo52n.png',
'src/assets/img/Clients/logo16.png',
'src/assets/img/Clients/logo17.png',
'src/assets/img/Clients/logo59.png'],
 [
    'src/assets/img/Clients/logo44.png',
    'src/assets/img/Clients/logo72.png',
    'src/assets/img/Clients/logo63.png',
    'src/assets/img/Clients/logo24.png',
    'src/assets/img/Clients/logo66.png',
    'src/assets/img/Clients/logo50.png',
    'src/assets/img/Clients/logo68.png',
    'src/assets/img/Clients/logo31.png',
    'src/assets/img/Clients/modern.png',
    'src/assets/img/Clients/logo34.png',
    'src/assets/img/Clients/school.png',
    'src/assets/img/Clients/logo42.png',
    'src/assets/img/Clients/logo53.png',
    'src/assets/img/Clients/logo45.png',
    'src/assets/img/Clients/logo46.png',
    'src/assets/img/Clients/logo55.png',
    'src/assets/img/Clients/logo41.png',
    'src/assets/img/Clients/logo89.png',
    'src/assets/img/Clients/logo32.png',
    'src/assets/img/Clients/logo9.png',
    'src/assets/img/Clients/logo7.png',
    'src/assets/img/Clients/logo63.png',
    'src/assets/img/Clients/logo47.png',
    'src/assets/img/Clients/logo75.png',
    'src/assets/img/Clients/logo35.png',
    'src/assets/img/Clients/logo39.png',
    'src/assets/img/Clients/logo61.png',
    'src/assets/img/Clients/logo49.png',
    'src/assets/img/Clients/logo14.png',
    'src/assets/img/Clients/logo12.png',
    'src/assets/img/Clients/logo60.png',
    'src/assets/img/Clients/logo58.png',
    'src/assets/img/Clients/logo22.png',
    'src/assets/img/Clients/Untitled-1-11.png',
    'src/assets/img/Clients/logo65.png',
    'src/assets/img/Clients/logo69.png',
    'src/assets/img/Clients/logo54.png',
    'src/assets/img/Clients/logo30.png',
    'src/assets/img/Clients/logo19.png',
    'src/assets/img/Clients/logo18.png',
    'src/assets/img/Clients/logo28.png',
    'src/assets/img/Clients/logo29.png',
    'src/assets/img/Clients/logo73.png']]


const Strips = () => {
  return (
    <div className='py-20 mt- w-full relative overflow-hidden'>
      {stripsImg.map((elem, index) => <Strip key={index} direction={index === 0 ? "left" : "right"} clientL={elem} /> )}
    </div>
  )
}

export default Strips